CREATE TABLE Users (
	rowid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	username TEXT NOT NULL ,
	password TEXT NOT NULL ,
	last_logged INTEGER NOT NULL 
);



CREATE TABLE Logs (
	rowid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	Users_rowid INTEGER NOT NULL ,
	text TEXT NOT NULL 
);



