<?xml version="1.0" encoding="utf-8"?><Database Class="NorthwindContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Customers">
    <Type Name="Customers">
      <Column Name="rowid" AutoSync="Never" Type="System.Int64" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" CanBeNull="false" />
      <Column Name="ContactTitle" Type="System.String" CanBeNull="false" />
      <Column Name="Address" Type="System.String" CanBeNull="false" />
      <Column Name="City" Type="System.String" CanBeNull="false" />
      <Column Name="Region" Type="System.String" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" CanBeNull="false" />
      <Column Name="Country" Type="System.String" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" CanBeNull="false" />
      <Column Member="Categories_rowid" Type="System.Int64" CanBeNull="false" />
      <Association Name="Customers_Categories" Member="Category" ThisKey="Categories_rowid" OtherKey="rowid" Type="Categories" />
    </Type>
  </Table>
  <Table Name="Categories">
    <Type Name="Categories">
      <Column Name="rowid" AutoSync="Never" Type="System.Int64" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" CanBeNull="false" />
      <Column Name="Description" Type="System.String" CanBeNull="false" />
      <Column Name="Picture" Type="System.Byte[]" CanBeNull="false" />
      <Association Name="Customers_Categories" Member="Customers" ThisKey="rowid" OtherKey="Categories_rowid" Type="Customers" IsForeignKey="true" />
    </Type>
  </Table>
</Database>