name: Build, Pack & Publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  Build:
    runs-on: windows-latest  
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Pack DtronixModel.Tools
      run: dotnet pack src/DtronixModel.Tools -c Release
      
    - name: Pack DtronixModel
      run: dotnet pack src/DtronixModel -c Release

    - name: Execute unit tests
      run: dotnet test src/DtronixModelTests
      
    - name: Create DtronixModeler installer
      run: dotnet publish src/DtronixModeler -c Release
      
    - name: Export artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts/*
        
    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      uses: olegtarasov/get-tag@v2.1
      id: tagName
      
    - name: Create changelog
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        "### Changelog" > ${{ github.workspace }}/CHANGELOG.TXT
        git log --pretty=format:"- %h %B" "$(git describe --tags --abbrev=0 "@^")..$(git describe --tags --abbrev=0 "@")" >> ${{ github.workspace }}/CHANGELOG.TXT
      
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "DtronixModel ${{ steps.tagName.outputs.tag }} Released"
        files: |
          artifacts/DtronixModel*.nupkg
          artifacts/DtronixModel*.snupkg
          artifacts/DtronixModeler-*.exe
        body_path: ${{github.workspace}}/CHANGELOG.TXT
        
    - name: Push Nuget packages
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.ORG_NUGET_AUTH_TOKEN }} --skip-duplicate
