name: .NET Core Desktop

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
        
    - name: Pack DtronixModel.Tools
      run: dotnet pack src/DtronixModel.Tools
      
    - name: Pack the DtronixModel
      run: dotnet pack src/DtronixModel

    - name: Execute unit tests
      run: dotnet test src/DtronixModelTests

    - name: Build DtronixModeler
      run: dotnet build src/DtronixModeler
      
    - name: Export nuget package artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts/*.nupkg
        
    - name: Push nuget packages.
      if: github.event_name == 'release'
      run: dotnet nuget push artifacts/*.nupkg
      
    